version: 2
jobs:
  java-base-test:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
    - run: mvn spotless:check animal-sniffer:check test verify
    - run:
        name: Test Failed
        when: on_fail
        command: |
          wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
          chmod u+x slack-notify-branch.sh
          BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
    - run: mvn package -B
    - save_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
    - persist_to_workspace:
        root: .
        paths:
        - .
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  test-jdklatest:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk
    steps:
    - checkout
    - restore_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
    - run: mvn spotless:check animal-sniffer:check test verify
    - run:
        name: Test Failed
        when: on_fail
        command: |
          wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
          chmod u+x slack-notify-branch.sh
          BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
    - run: mvn package -B
    - save_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
    - persist_to_workspace:
        root: .
        paths:
        - .
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  test-jdk11:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:11-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
    - run: mvn spotless:check animal-sniffer:check test verify
    - run:
        name: Test Failed
        when: on_fail
        command: |
          wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
          chmod u+x slack-notify-branch.sh
          BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
    - run: mvn package -B
    - save_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
    - persist_to_workspace:
        root: .
        paths:
        - .
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  test-jdk8:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
    - run: mvn spotless:check animal-sniffer:check test verify
    - run:
        name: Test Failed
        when: on_fail
        command: |
          wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
          chmod u+x slack-notify-branch.sh
          BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
    - run: mvn package -B
    - save_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
    - persist_to_workspace:
        root: .
        paths:
        - .
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  test:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:11-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
    - run: mvn spotless:check animal-sniffer:check test verify
    - run:
        name: Test Failed
        when: on_fail
        command: |
          wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
          chmod u+x slack-notify-branch.sh
          BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
    - run: mvn package -B
    - save_cache:
        key: maven-dep-cache-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
    - persist_to_workspace:
        root: .
        paths:
        - .
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  publish:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: .buildscript/deploy_snapshot.sh
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
    - CIRCLE_JDK_VERSION: oraclejdk8
  coverage:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: mvn cobertura:cobertura
    - run: bash <(curl -s https://codecov.io/bash)
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  e2e:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: .buildscript/e2e.sh
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
  snyk:
    working_directory: ~/analytics-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Snyk
        command: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh
        environment:
          SNYK_FAIL_ON: upgradable
          SNYK_SEVERITY_THRESHOLD: high
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/North-Two-Five/analytics-java/compare/69f074caaa19ee7753725ca727b1d506ae19d9c2...69f074caaa19ee7753725ca727b1d506ae19d9c2
workflows:
  version: 2
  multi-test:
    jobs:
    - test-jdklatest
    - test-jdk11
    - test-jdk8
  static_analysis:
    jobs:
    - test
    - coverage:
        requires:
        - test
    - snyk:
        context: snyk
        requires:
        - test
  test_and_publish:
    jobs:
    - test:
        filters:
          branches:
            only: master
    - publish:
        requires:
        - test
        filters:
          branches:
            only: master
  scheduled_e2e_test:
    triggers:
    - schedule:
        cron: 5 * * * *
        filters:
          branches:
            only:
            - master
            - scheduled_e2e_testing
    jobs:
    - test
    - e2e:
        requires:
        - test
